### ISSUE TITLE
Unable to load scss file correctly

### ISSUE THREAD

**Issue by prakhargvp** [leonardomso/react-bolt#17]
SCSS File is not loading properly

![Screenshot from 2019-12-14 09-57-22](https://user-images.githubusercontent.com/7056772/70843454-634a7200-1e58-11ea-9ad9-8b1487b94527.png)

![Screenshot from 2019-12-14 09-58-12](https://user-images.githubusercontent.com/7056772/70843456-65accc00-1e58-11ea-94b4-74ad4aff492f.png)

![Screenshot from 2019-12-14 09-58-41](https://user-images.githubusercontent.com/7056772/70843457-66ddf900-1e58-11ea-868f-1d0d3260f64d.png)

**Comment by leonardomso** [comment]
Yes, this is a point that's is missing in this boilerplate, please feel free to send a PR.

**Comment by prakhargvp** [comment]
Hi!, I send a PR.

**Comment by leonardomso** [comment]
PR merged.
