### ISSUE TITLE
Graphql tag

### ISSUE THREAD

**Issue by diegoarcega** [leonardomso/react-bolt#6]
This project has the graphql tag in it but no graphql is set up, misleading, can you remove it?

**Comment by leonardomso** [comment]
I don't know why I installed it, please open a PR and remove it!

**Comment by diegoarcega** [comment]
I mean, this `tag` 
![image](https://user-images.githubusercontent.com/1951007/56229353-1d7ea500-6050-11e9-8052-e297ed3745ca.png)

**Comment by leonardomso** [comment]
Removed!
